### ISSUE TITLE
Medical Org: New order

### ISSUE THREAD

**Issue by tinataleb** [C19-BayShield/bayshield#60]
![Frame 51](https://user-images.githubusercontent.com/21226461/84716769-edb77f80-af28-11ea-8348-52b49fcca7bf.png)
![Frame 52](https://user-images.githubusercontent.com/21226461/84716770-ee501600-af28-11ea-97f7-3655f756d906.png)

**Comment by emily-zhu** [comment]
orders UI completed with PR #63 
TODO: backend implementation
